task #5
ozonva/ova-conference-api pull request #6
Opened 2021-08-22 21:44 UTC by HMXyber

Нужно в пакете saver имплементировать Saver интерфейс, с возможностью писать в хранилище данные, через Flusher, сброс данных происходит во flusher по определенному таймауту или при вызове метода Close
До сброса в хранилище, данные хранятся в slice. который принадлежит saver-у.
Установка capacity данного slice-a идет на этапе конструирование -  при вызове NewSaver

2021-08-23 11:41 UTC, kshmatov requested changes

2021-08-23 11:41 UTC, kshmatov commented on internal/utils/saver/saver.go
> +func (rep repository) awaitingFlush() {
Вот здесь ошибка.
В flush ты закрываешь closeChanel, после этого селект будет ВСЕГДА считывать первый вариант, при этом никаких задержек не  будет.
Гарантируется, что в select варианты срабатывают в порядке упоминания, а закрытый канал мгновенно отдает пустое значение.

2021-08-23 11:41 UTC, kshmatov commented on internal/utils/saver/saver.go
> +		rep.closeChanel <- true
Достаточно закрыть канал, не обязательно в него писать. Кроме того, это помогает избежать ошибок с повисшими горутинами, которые будут ждать данных из канала.

2021-08-23 19:58 UTC, HMXyber commented on internal/utils/saver/saver.go
> +func (rep repository) awaitingFlush() {
спасибо. меня спасал получается sync.once от второго срабатывания

2021-08-24 12:01 UTC, kshmatov approved these changes

2021-08-24 12:06 UTC, merged